package com.ds.travel.travelandroid.model;
// Generated Oct 7, 2016 12:53:25 PM by Hibernate Tools 5.1.0.Alpha1

import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable{

	private Integer id;
	private Profile profile;
	private String username;
	private String email;
	private String password;
	private Date createdAt;
	private Date updatedAt;
	private Set travels = new HashSet(0);
	private Set countryUsers = new HashSet(0);
	private Set messages = new HashSet(0);

	public User() {
	}

	public User(Profile profile, String username, String email, String password, Date createdAt, Date updatedAt,
			Set travels, Set countryUsers, Set messages) {
		this.profile = profile;
		this.username = username;
		this.email = email;
		this.password = password;
		this.createdAt = createdAt;
		this.updatedAt = updatedAt;
		this.travels = travels;
		this.countryUsers = countryUsers;
		this.messages = messages;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Profile getProfile() {
		return this.profile;
	}

	public void setProfile(Profile profile) {
		this.profile = profile;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public Date getCreatedAt() {
		return this.createdAt;
	}

	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	public Date getUpdatedAt() {
		return this.updatedAt;
	}

	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	public Set getTravels() {
		return this.travels;
	}

	public void setTravels(Set travels) {
		this.travels = travels;
	}

	public Set getCountryUsers() {
		return this.countryUsers;
	}

	public void setCountryUsers(Set countryUsers) {
		this.countryUsers = countryUsers;
	}

	public Set getMessages() {
		return this.messages;
	}

	public void setMessages(Set messages) {
		this.messages = messages;
	}

}
